baseURL = "https://martinsda.github.io/martinsda.io/"
languageCode = "en-us"
title = "Daniel Martins"
theme = "resume"


[params]
    firstName = "Daniel"
    lastName = "Martins"
    address = "Lisbon, Portugal"
    phone = "+351 91906735"
    contactNote = "Consultant"
    profileImage = "img/IMG2.jpg"
    email = "info@danielmartins.org"
    emailencoded = "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%69%6E%66%6F%40%64%61%6E%69%65%6C%6D%61%72%74%69%6E%73%2E%6F%72%67"
    description = "OutSystems Professional Developer, solution analysist and developer, IT Consultant"
    keywords = "Outsystems, Outsystems Developer, web developer, consultant, java, ruby, ruby on rails, php, web development, mysql, web applications developer"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dmartins/"

[[params.handles]]
    name = "Medium"
    link = "https://medium.com/@martinsda/"


[params.google.analytics]
    trackerID = "XX-123446-01"

